project_id = "wukqjztyhzkqimnzybae"

[functions.send-push-notification]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
